#!/bin/bash

file=$1
username=$2

if [$# -ne 2]
then
	echo"Incorrect no of arguments"
	exit 1
fi


if [-f "$file" ]
then
	echo"file found"
	exit 1
else
	echo"File nt found"

if grep-i-w"$username"$file
then 
	echo "ZUsername already exist"
else
		echo "usernsame not found"
